# Site settings
title: summer's devFolio
description: summer's devFolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:4000" the base hostname & protocol for your site e.g. http://wnajoah.github.io


# User settings
username: Shin yeoruem
user_description: 안녕하세요! 개발자로서 현실과 디지털 세계를 연결하여, 세상 많은 이들의 편리함에 도움이 되고싶은 신여름입니다. 새로운 일에 도전하며 배워나가는 것에 관심이 많고, 적극적인 소통으로 원활한 협업을 위해 노력합니다. 또한, 현실에 안주하지 않고 자신을 발전시키는 것에 성취감을 느낍니다. 꾸준한 독서와 주기적인 운동을 통해 건강하고 쾌적한 컨디션을 유지하고 있습니다. 아직 배울 점이 많은 새내기 개발자이지만, 빠르게 실무에 익숙해질 수 있도록 열정적으로 공부하고 끊임 없이 성장하는 모습 보여드리겠습니다. 잘 부탁드립니다.
# user_title: Developer
email: wnajoah@gmail.com
#twitter_username: lorem_ipsum
github_username:  wnajoah
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
